#Amplicon sequencing for 16S rDNA in the whole body of aphids of Tetraneura akinire (TA), T.sorini (TS) and E.harunire (EH)across the whole life cycles.
#s1-s5:Foundress,2nd gen,root gen,sexual female,and male generation (TS)
#s6-10:TA
#s11-12:gall generation, root generation (EH)
#Sample list
220308-XTm1_S10_L001_R1_001.fastq  220308-XTm1_S12_L001_R2_001.fastq  220308-XTm1_S3_L001_R1_001.fastq  220308-XTm1_S5_L001_R2_001.fastq  220308-XTm1_S8_L001_R1_001.fastq
220308-XTm1_S10_L001_R2_001.fastq  220308-XTm1_S1_L001_R1_001.fastq   220308-XTm1_S3_L001_R2_001.fastq  220308-XTm1_S6_L001_R1_001.fastq  220308-XTm1_S8_L001_R2_001.fastq
220308-XTm1_S11_L001_R1_001.fastq  220308-XTm1_S1_L001_R2_001.fastq   220308-XTm1_S4_L001_R1_001.fastq  220308-XTm1_S6_L001_R2_001.fastq  220308-XTm1_S9_L001_R1_001.fastq
220308-XTm1_S11_L001_R2_001.fastq  220308-XTm1_S2_L001_R1_001.fastq   220308-XTm1_S4_L001_R2_001.fastq  220308-XTm1_S7_L001_R1_001.fastq  220308-XTm1_S9_L001_R2_001.fastq
220308-XTm1_S12_L001_R1_001.fastq  220308-XTm1_S2_L001_R2_001.fastq   220308-XTm1_S5_L001_R1_001.fastq  220308-XTm1_S7_L001_R2_001.fastq

1. convert fastq to fasta
#forR1
for file in 220308-XTm1_S*_L001_R1_001.fastq; do
    sample=$(echo $file | sed 's/220308-XTm1_S\([0-9]*\)_L001_R1_001.fastq/s\1_r1.fasta/')
    seqtk seq -A $file > $sample
done
#forR2
for file in 220308-XTm1_S*_L001_R2_001.fastq; do
    sample=$(echo $file | sed 's/220308-XTm1_S\([0-9]*\)_L001_R2_001.fastq/s\1_r2.fasta/')
    seqtk seq -A $file > $sample
done

2. preview the quality of the reads by fastqc and MAFFT
3. extract V1-V2 reads and V3-V4 reads
#since I amplified V1-V2 and V3-V4 separately but sequenced them together, this is for extracting respective reads
16S V1-V2 Primer Sequences (adapters not included) –27f(AGRGTTYGATYMTGGCTCAG, 20 bp) and 341r(CTGCWGCCHCCCGTAGG, 17 bp)
16S V3-V4 Primer Sequences (adapters not included) – 341f(CCTACGGGDGGCWGCAG, CCTAYGGGGYGCWGCAG, 17bp) and 806r (GACTACNVGGGTMTCTAATCC, 24 bp). 
The forward primer 341f is a mixture of the two sequences listed.

$For V1-V2,
forward_primer_v1v2="AGRGTTYGATYMTGGCTCAG"
reverse_primer_v1v2="CTGCWGCCHCCCGTAGG"

adapter_output="adapter_overview_all_samples_v1v2.txt"

if [ ! -f $adapter_output ]; then
  echo "Creating the adapter output file: $adapter_output"
  touch $adapter_output
fi

for sample in {1..12}
do
  sample_id="S${sample}"
  
  R1_input="220308-XTm1_${sample_id}_L001_R1_001.fastq"
  R2_input="220308-XTm1_${sample_id}_L001_R2_001.fastq"
  
  R1_output="trimmed_${sample_id}_V1V2_R1.fastq"
  R2_output="trimmed_${sample_id}_V1V2_R2.fastq"
  
  untrimmed_R1="unassigned_${sample_id}_V1V2_R1.fastq"
  untrimmed_R2="unassigned_${sample_id}_V1V2_R2.fastq"
  
  echo "Processing files: $R1_input and $R2_input"
  
  cutadapt -g $forward_primer_v1v2 -a $reverse_primer_v1v2 \
    --untrimmed-output $untrimmed_R1 -o $R1_output $R1_input 2>&1 | tee -a $adapter_output
  
  cutadapt -g $forward_primer_v1v2 -a $reverse_primer_v1v2 \
    --untrimmed-output $untrimmed_R2 -o $R2_output $R2_input 2>&1 | tee -a $adapter_output
  
  echo "Sample ${sample_id} processed: $R1_output and $R2_output"
done

echo "All adapter overview data for V1-V2 has been written to $adapter_output"


$For V3-V4_R1
#!/bin/bash

forward_primer_1="CCTACGGGDGGCWGCAG"
forward_primer_2="CCTAYGGGGYGCWGCAG"
reverse_primer="GACTACNVGGGTMTCTAATCC"

adapter_output="adapter_overview_all_samples.txt"

if [ ! -f $adapter_output ]; then
  echo "Creating the adapter output file: $adapter_output"
  touch $adapter_output
fi

for sample in {1..12}
do
  sample_id="S${sample}"
  R1_input="220308-XTm1_${sample_id}_L001_R1_001.fastq"  
  R2_input="220308-XTm1_${sample_id}_L001_R2_001.fastq"
  
  R1_output="trimmed_${sample_id}_V3V4_R1.fastq"
  R2_output="trimmed_${sample_id}_V3V4_R2.fastq"
  
  untrimmed_R1="unassigned_${sample_id}_V3V4_R1.fastq"
  untrimmed_R2="unassigned_${sample_id}_V3V4_R2.fastq"
  
  echo "Processing files: $R1_input and $R2_input"
  
  cutadapt -g $forward_primer_1 -a $reverse_primer \
    --untrimmed-output $untrimmed_R1 -o $R1_output $R1_input 2>&1 | tee -a $adapter_output
  
  cutadapt -g $forward_primer_2 -a $reverse_primer \
    --untrimmed-output $untrimmed_R2 -o $R2_output $R2_input 2>&1 | tee -a $adapter_output
  
  echo "Sample ${sample_id} processed: $R1_output and $R2_output"
done

echo "All adapter overview data has been written to $adapter_output"

4. Qiime2
$nano manifest.csv
sample-id,absolute-filepath,direction
S1,/pathtofastq/trimmed_S1_V1V2_R1.fastq,forward
S1,/pathtofastq/trimmed_S1_V1V2_R2.fastq,reverse
S2,/pathtofastq/trimmed_S2_V1V2_R1.fastq,forward
...

-import 
$qiime tools import 
>   --type 'SampleData[PairedEndSequencesWithQuality]' \
>   --input-path manifest.csv \
>   --output-path demux.qza \
>   --input-format PairedEndFastqManifestPhred33
（but forward read quality is not ideal for later analysis so switch to single-end > using reverse reads)

-import again (reverse reads only)
$qiime tools import \
  --type 'SampleData[SequencesWithQuality]' \
  --input-path manifest_r.csv \
  --output-path demux_reverse.qza \
  --input-format SingleEndFastqManifestPhred33V2
 
$qiime dada2 denoise-single \
  --i-demultiplexed-seqs demux_reverse.qza \
  --p-trim-left 17 \
  --p-trunc-len 200 \
  --p-max-ee 2 \
  --o-table table_reverse.qza \
  --o-representative-sequences rep-seqs_reverse.qza \
  --o-denoising-stats stats_reverse.qza
-denoise
$qiime vsearch uchime-denovo   
--i-table table_reverse.qza   
--i-sequences rep-seqs_reverse.qza   
--o-chimeras chimeras_reverse.qza   
--o-nonchimeras nonchimeras_reverse.qza   
--o-stats uchime-stats_reverse.qza

wget https://www.arb-silva.de/fileadmin/silva_databases/current/Exports/SILVA_138.2_SSURef_NR99_tax_silva.fasta.gz
sed 's/U/T/g' SILVA_138.2_SSURef_NR99_tax_silva.fasta > SILVA_138.2_SSURef_NR99_tax_silva_corrected.fasta
$ qiime tools import \
>   --type 'FeatureData[Sequence]' \
>   --input-path SILVA_138.2_SSURef_NR99_tax_silva_corrected.fasta \
>   --output-path silva_138_2_ssu_ref_nr99_seqs.qza


